# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureResourceManagerTemplateDeployment@3
  name: DeployResourceGroup
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Visual Studio Professional(47df455b-f3c1-4e50-a88d-ff6a59939ec0)'
    subscriptionId: '47df455b-f3c1-4e50-a88d-ff6a59939ec0'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/Templates/ResourceGroup/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/Templates/ResourceGroup/template.parameters.json'
    deploymentMode: 'Incremental'
- task: AzureResourceManagerTemplateDeployment@3
  name: DeployKeyVault
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Professional(47df455b-f3c1-4e50-a88d-ff6a59939ec0)'
    subscriptionId: '47df455b-f3c1-4e50-a88d-ff6a59939ec0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureIntegrationDemoRG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/Templates/KeyVault/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/Templates/KeyVault/template.parameters.json'
    deploymentMode: 'Incremental'
- task: AzureResourceManagerTemplateDeployment@3
  name: DeployServiceBus
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Professional(47df455b-f3c1-4e50-a88d-ff6a59939ec0)'
    subscriptionId: '47df455b-f3c1-4e50-a88d-ff6a59939ec0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureIntegrationDemoRG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/Templates/ServiceBus/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/Templates/ServiceBus/template.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: servicebustemplateoutput
- pwsh: |
    $armOutputObj = '$(servicebustemplateoutput)' | convertfrom-json
    $connectionString = $armOutputObj.namespaceConnectionString.value
    Write-Output "##vso[task.setvariable variable=ServiceBusConnectionString;issecret=true]$connectionString"
- task: cboroson-WriteSecrets@1
  displayName: WriteSecrets
  inputs:
    ConnectedServiceName: 'Visual Studio Professional(47df455b-f3c1-4e50-a88d-ff6a59939ec0)'
    resourceGroupName: 'AzureIntegrationDemoRG'
    KeyVaultName: 'aikv2034'
    SecretName: 'ServiceBusConnectionString'
    SecretValue: '$(ServiceBusConnectionString)'


